@echo off
setlocal
REM chiikawa.cmd — Windows launcher for the OhMyChiikawa desktop pet CLI.
REM Supports the same commands as chiikawa.js: start, pets, pack, version, help.
REM Node.js 18+ is required.
REM
REM Usage:
REM   chiikawa [start] [options]
REM   chiikawa pets
REM   chiikawa pack
REM   chiikawa version
REM   chiikawa help
REM
REM After `npm link` or `npm install -g`, this wrapper is auto-generated by npm.
REM This file lets you run `chiikawa` directly from the project root without
REM linking, e.g.:
REM   .\chiikawa.cmd
REM   .\chiikawa.cmd --size small
REM   .\chiikawa.cmd -p usagi -s large

node "%~dp0chiikawa.js" %*
exit /b %errorlevel%
